### ISSUE TITLE
Suggestion, ability to remove instruction from AST in xrefs.

### ISSUE THREAD

**Issue by Tonyx97** [0xeb/ida-strikeout#2]
Hello, I'm using this plugin for a few weeks now, works great to remove useless stuff like exception handling variables that serve no purpose in analyzing. There is one thing that could help a lot though, and that's the ability to remove the instructions from xref window (or in a similar way). In my case, the assignments for v95 are completely useless and makes analyzing annoying, I'd love to see a batch instruction removal in the future. Thanks for your plugin!

https://user-images.githubusercontent.com/12673334/183776373-c747e5be-233c-4799-92f1-b91ed0dfeb07.mp4

t

**Comment by 0xeb** [comment]
@Tonyx97 , sorry for the late reply. For that, you need to patch out. StrikeOut has the option to apply the changes (the lines you deleted) by automatically applying "NOPs". 
1. Delete the line
2. Press Alt-Shift-Ins
3. Press Alt-Shift-End

Like this the line deletions will be permanent and will be replaced by NOPs.
